### ISSUE TITLE
How to introduce mvn clean into Action?

### ISSUE THREAD

**Issue by celanthe** [camunda-community-hub/community-action-maven-release#15]
See https://github.com/camunda-community-hub/camunda-bpm-identity-keycloak/actions/runs/1015734640 for more information. 

@VonDerBeck has also provided the following information in: https://github.com/camunda-community-hub/camunda-bpm-identity-keycloak/issues/67#issuecomment-878113852

The `build` pipeline calls `mvn-clean-package` and works. However, the `deploy` pipeline still fails. 

Question: How can one run the community-action-maven-release successfully and include the `mvn clean` command? Furthermore, how can `mvn clean` be included in the release action by default?

**Comment by VonDerBeck** [comment]
See https://github.com/camunda-community-hub/community-action-maven-release/pull/16#issuecomment-879627820

From my side there is no need for further action and this issue can be closed.

**Comment by celanthe** [comment]
> See [#16 (comment)](https://github.com/camunda-community-hub/community-action-maven-release/pull/16#issuecomment-879627820)
> 
> From my side there is no need for further action and this issue can be closed.

Hi @VonDerBeck, thank you for the update! I'll close this issue, then! :) Glad we were able to resolve things! :D
