### ISSUE TITLE
Check if v1.0.9 should overwrite v1 tag

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/community-action-maven-release#25]
I just release 1.0.9 and this should probably be used whenever v1 is used - but I am unsure how we exactly envision to do this and want to leave it up to @celanthe

**Comment by celanthe** [comment]
Hi @berndruecker, yes, that makes sense. That's what I was trying to say in the above comment. :) I can do that, yes.

**Comment by berndruecker** [comment]
Great - looking forward to it 👍

**Comment by berndruecker** [comment]
I just double-checked and looking at https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsuses it looks like using "v1" for the action automatically uses the latest minor version for that: 

> Using the specific major action version allows you to receive critical fixes and security patches while still maintaining compatibility. It also assures that your workflow should still work.

So this might mean there is even thing to do from my perspective here - sorry for the confusion (just double-checked when I saw the changes)

**Comment by celanthe** [comment]
Oh, I see! @berndruecker, would this mean that as long as we continue to follow semantic versioning, the action will continue to work? It's interesting to note that this [according to the documentation linked in your comment] persists through v2 and onward. 

If there is nothing to do in this case, I am happy to close my pending PR! :)

**Comment by berndruecker** [comment]
This is exactly how I understand it and yes - I think you can close this issue because of that :-)

**Comment by berndruecker** [comment]
Seems I was wrong - when I changed my action to do "v1" it gave me some error messages it does not find the parameters that should actually be present in the latest version within v1 (v1.0.9): https://github.com/camunda-community-hub/spring-zeebe/actions/runs/1461919982

**Comment by celanthe** [comment]
No worries @berndruecker, I just re-opened https://github.com/camunda-community-hub/community-action-maven-release/pull/27 and I hope that will get us a step closer to resolving this! :)
