### ISSUE TITLE
enhancement(ci): Close repositories after staging by default

### ISSUE THREAD

**Issue by celanthe** [camunda-community-hub/community-action-maven-release#33]
**Steps to reproduce the issue/bug**

Perform a release using the Community Action Maven Release tool
Staging repositories are still open after the release is finished

**What's the expected result of implementing this feature?**

By implementing this feature, repositories will be closed automatically after staging by default

**Estimated timeline:**

1-2 weeks

**TODO:**

1. Scope implementing the https://github.com/nexus-actions/release-nexus-staging-repo tool into the existing Community Action workflow.
2. Open PR with the above changes added 
3. Test and confirm that the new feature is working as intended
4. Merge PR
3. Cut new release introducing this feature into the Community Action Maven Release

**Comment by berndruecker** [comment]
As far as I remember, @zambrovski had some comment about it - but I don't recall what exactly :-/

**Comment by zambrovski** [comment]
We had a nice meeting before the new day...

**Comment by berndruecker** [comment]
@zambrovski I think we should auto-close it. I also don't see any reason against it (but some confusion it caused already). Do you know how we can easily set this to auto-close the repo?

A hint would be great - but of course I also take PR's :-)

**Comment by zambrovski** [comment]
Will continue to do it here, as we obviously need as described in https://github.com/camunda-community-hub/camunda-platform-7-mockito/issues/260

**Comment by zambrovski** [comment]
Implemented. Please check...

**Comment by zambrovski** [comment]
@berndruecker : I created an example project which should serve as an example using the entire CI/CD infrastructure (Maven parent + GH actions). It is then creates a small artifact doing nothing, but we can use it to make sure the CI/CD setup works for the other 200 repositories of HUB.

So I suggest, we really produce artifacts there to really be sure it works as designed.
