### ISSUE TITLE
 authentication failed

### ISSUE THREAD

**Issue by pierre-yves-monnet** [camunda-community-hub/community-action-maven-release#39]
I try to deploy https://github.com/camunda-community-hub/zeebe-cherry-framework

I added the parent in the pom.xml (can we do differently? I would like to keep spring-boot as a parent).

I created a [deploy.yaml](https://github.com/camunda-community-hub/zeebe-cherry-framework/tree/main/.github)/workflows/deploy.yaml). 

I copy the one given in the README, and I just changed the version to "17" (line 22)
`          java-version: "17"`

I created a Release, and I tagged it "latest"
https://github.com/camunda-community-hub/zeebe-cherry-framework/releases/tag/v1.3.2

Deploy SNAPSHOT/Release failed: Check the result:

https://github.com/camunda-community-hub/zeebe-cherry-framework/actions/runs/3340618838/jobs/5580931013

`Error:  Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy (default-deploy) on project zeebe-cherry-framework: Failed to deploy artifacts: Could not transfer artifact org.camunda.community:zeebe-cherry-framework:jar:1.3.2 from/to camunda-nexus (https://artifacts.camunda.com/artifactory/camunda-bpm-community-extensions/): authentication failed for https://artifacts.camunda.com/artifactory/camunda-bpm-community-extensions/org/camunda/community/zeebe-cherry-framework/1.3.2/zeebe-cherry-framework-1.3.2.jar, status: 401 Unauthorized -> [Help 1]
`

Thank you for your help

**Comment by berndruecker** [comment]
I think the credentials need to be added to the repo.

See https://github.com/camunda-community-hub/community/blob/main/RELEASE.MD --> https://github.com/camunda-community-hub/infrastructure#use-case-onboarding-a-new-community-hub-repository 

So the repo needs to be added to https://github.com/camunda-community-hub/infrastructure/edit/master/terraform/github/repositories.tf via PR first. After merging the credentials will be added

**Comment by pierre-yves-monnet** [comment]
It was exactly that. Thank you!
the library is not visible here:
https://artifacts.camunda.com/ui/native/camunda-bpm-community-extensions/org/camunda/community/zeebe-cherry-framework/1.3.2/
