### ISSUE TITLE
Release new version of the action

### ISSUE THREAD

**Issue by zambrovski** [camunda-community-hub/community-action-maven-release#43]
Dear @camunda-community-hub/devrel,

I suggest to release this action in a new version. This would allow to use the new features of:

- test result publication #34 
- auto release on close #33 

Before doing this, please let us activate the repository https://github.com/camunda-community-hub/community-hub-extension-example/ and use it as a test to produce the 1.0.0 release there (it uses this action version from the `main` branch).

To do so, there must be GH secrets, required for the publication (as described in https://github.com/camunda-community-hub/community-hub-extension-example/issues/1).

Cheers,

Simon

**Comment by berndruecker** [comment]
Howdy @zambrovski - just saw this issue now - I think it is fixed as we released two new version in the meantime: https://github.com/camunda-community-hub/community-action-maven-release/releases. Please object if not!
