### ISSUE TITLE
Release Action formats code

### ISSUE THREAD

**Issue by jonathanlukas** [camunda-community-hub/community-action-maven-release#44]
The release action formats code, breaking our repo code format at exactly one point:

https://github.com/camunda-community-hub/camunda-7-to-8-migration/commit/ca58db474836a8f1bb5573393e1ad502197fb579#diff-62a928c9d3b1fa53272b907bdd4fd9d69a97aa2d9d44944f21b646a389ec8cda

We are using spotless, however adding `-Dspotless.apply.skip` (which skips the auto-formatter) as `maven-release-options` did have no effect.

Is there another plugin used from your side that would format code?

**Comment by berndruecker** [comment]
Hi @jonathanlukas - we updated the Maven parent pom and release action - can you try again with the latest parent (1.4.0) and release action if `-Dspotless.apply.skip` still does not work for your project? 

I am closing this for now - please reopen if still a problem!
