### ISSUE TITLE
Release 1.1 of the action.

### ISSUE THREAD

**Issue by zambrovski** [camunda-community-hub/community-action-maven-release#50]
Hi @berndruecker,

I checked the problems reported in different repositories regarding the problems of the releases (duplicate release) and fixed the action. 

Before doing more refactoring, let release current version of the action and give it a 1.1 tag.

**Comment by berndruecker** [comment]
Could be done in tandem with https://github.com/camunda-community-hub/community-hub-release-parent/issues/19

**Comment by berndruecker** [comment]
https://github.com/camunda-community-hub/community-action-maven-release/releases/tag/v1.1.0
