### ISSUE TITLE
Maven release action needs to push changed version number

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/community-action-maven-release#6]
The Maven Release Action copied from https://github.com/camunda-community-hub/community-action-maven-release
does not set the version number of the release in the created Github tag

See https://github.com/camunda-community-hub/kafka-connect-zeebe/blob/0.31.0/pom.xml#L10 (is 1.0.0-SNAPSHOT but must be 0.31.0

Looks like the action does not commit or push the adjusted version number to the Github tag

**Comment by celanthe** [comment]
Hi @berndruecker! Thank you for opening this issue. Based on my initial research, there appear to be a few ways to resolve this.

1.  Potentially trying this workflow or modifying the existing workflow to:
```on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
```
2.   Add a step to the existing action that uses the variable tag_version tags a release by running the following workflow in the action:
```steps:
      - uses: actions/checkout@v2
      - name: bump version and push tag
        id: tag_version
        if: ${{ github.event_release== 'push' && runner.os == 'Linux' && matrix.java == '11' }}
        uses: github.event.release/github-tag-action@vx.x
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_annotated_tag: true
```

The release workflow that's already in use currently makes use of ` release-version: ${{ github.event.release.tag_name }}` and I'm struggling a bit to understand further why it's not pushing changed version numbers. @Langleu would you be able to verify if either of these approaches might work to solve the issue @berndruecker listed above?

**Comment by Langleu** [comment]
Good point, on the bright side the version linked in the release is actually the one you defined and not 1.0.0.

I think the only proper solution would be to adjust [the function of the GitHub Action](https://github.com/camunda-community-hub/community-action-maven-release/blob/main/resources/prepare-next-development-version.sh).

I created a ticket in Jira to actually work on it. Likely just recreate/force-push the updated tag but will try that out on a test repository.

**Comment by Langleu** [comment]
@berndruecker , pushed the fixed and updated the `v1` tag to use the latest changes. It should now properly overwrite the release tag with the updated release version in the pom.xml

**Comment by berndruecker** [comment]
Great - thx - that was quick!
